### ISSUE TITLE
Why not use an .env file?

### ISSUE THREAD

**Issue by QasimWani** [computer-geek64/blackout#1]
Interesting idea... but why not just make use of an environment file that keeps track of your API credentials and using gotignore on that?

**Comment by computer-geek64** [comment]
You are right, that is what you are generally supposed to do for projects, create a configuration/environment file to store any secrets. However, not everyone is perfect 100% of the time, and sometimes people mess up and end up committing sensitive information to their repository.

Those cases are what **Blackout** was made for, as an efficient tool to go back through your commit history and cover up that sensitive information.

**Comment by varunlakshmanan** [comment]
@QasimWani I agree. An environment file has mostly the same functionality.
